import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  logo: <span>aaaa</span>,
  project: {
    link: 'https://github.com/Jolli-sample-repos/aaa',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/aaa',
  footer: {
    text: 'aaaa - Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – aaaa'
    }
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="aaaa" />
      <meta property="og:description" content="Documentation for aaaa" />
    </>
  )
}

export default config
